version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo "Docker Login..."
      - echo $PASSWORD | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t coworking-analytics:$CODEBUILD_BUILD_NUMBER ./analytics
      - docker tag coworking-analytics:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/turkialq/udacity:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/turkialq/udacity:$CODEBUILD_BUILD_NUMBER
      - echo Build completed on `date`